name: getwidget_example
description: GetWidget Demo App

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  getwidget:
    path: ../
  flutter_svg: ^0.19.0
  url_launcher: ^5.6.0
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  import_sorter: ^4.2.1

flutter:
  uses-material-design: true

  assets:
    - assets/github.svg
    - assets/logo.svg
    - assets/playstore.svg

