name: getwidget
description: GetWidget is an open source library that comes with 1000+ pre-built
  UI components. It makes development faster & more enjoyable. You can also
  customize the component as per your needs.
version: 1.1.3
homepage: https://github.com/ionicfirebaseapp/getwidget

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  import_sorter: ^4.2.1

flutter:
  uses-material-design: true

