name: getwidget
description: GetWidget is an open source library that comes with 1000+ pre-built
  UI components. It makes development faster & more enjoyable. You can also
  customize the component as per your needs.
version: 1.1.3
homepage: https://github.com/ionicfirebaseapp/getwidget

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ? Only here for `example\lib\main.dart`.
  # TODO: Remove once code has been cleaned up entirely.
  flutter_svg: ^0.19.0
  url_launcher: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # TODO: Remove once code has been cleaned up entirely.
  import_sorter: ^4.2.1

flutter:
  uses-material-design: true

  fonts:
    # Text Fonts
    - family: Maven Pro
      fonts:
        - asset: assets/fonts/MavenPro-Black.ttf
          weight: 900
        - asset: assets/fonts/MavenPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/MavenPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/MavenPro-Regular.ttf
          weight: 400
